name: Test hpxml_version_translator

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: PyTest and Coverage
        run: python -m pytest --junitxml=coverage/junit.xml --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/htmlreport --cov=hpxml_version_translator -n auto
        continue-on-error: true
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: ${{ matrix.python-version == 3.9 }}
        with:
          report_paths: coverage/junit.xml
          check_name: Testing Report
          fail_on_failure: true
      - name: Upload Coverage
        if: ${{ matrix.python-version == 3.9 }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report
          path: coverage/htmlreport/
      - name: Report Coverage to Pull Request
        uses: 5monkeys/cobertura-action@v14
        if: ${{ matrix.python-version == 3.9 }}
        with:
          path: coverage/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 98
          skip_covered: false
          show_missing: true
      - name: Linting
        uses: psf/black@stable
